SET GLOBAL local_infile = 1;
SHOW VARIABLES LIKE 'local_infile';

DELETE FROM payments;
DELETE FROM stations;
DELETE FROM rentals;
DELETE FROM scooters;
DELETE FROM users;
DELETE FROM city;
DELETE FROM price;

LOAD DATA LOCAL INFILE 'csv/city.csv'
INTO TABLE city
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'
IGNORE 1 LINES
;



LOAD DATA LOCAL INFILE 'csv/users.csv'
INTO TABLE users
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'

IGNORE 1 LINES
;



LOAD DATA LOCAL INFILE 'csv/scooters.csv'
INTO TABLE scooters
CHARSET utf8
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


LOAD DATA LOCAL INFILE 'csv/stations.csv'
INTO TABLE stations
CHARSET utf8
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;


LOAD DATA LOCAL INFILE 'csv/rentals.csv'
INTO TABLE rentals
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'

IGNORE 1 LINES
;



LOAD DATA LOCAL INFILE 'csv/payments.csv'
INTO TABLE payments
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'

IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE 'csv/price.csv'
INTO TABLE price
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'
IGNORE 1 LINES
;