

SET GLOBAL local_infile = 1;
SHOW VARIABLES LIKE 'local_infile';

DELETE FROM city;
LOAD DATA LOCAL INFILE './db/csv/city.csv'
INTO TABLE city
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'
IGNORE 1 LINES
;




DELETE FROM users;
LOAD DATA LOCAL INFILE './db/csv/users.csv'
INTO TABLE users
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'

IGNORE 1 LINES
;


DELETE FROM scooters;
LOAD DATA LOCAL INFILE './db/csv/scooters.csv'
INTO TABLE scooters
CHARSET utf8
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

DELETE FROM stations;
LOAD DATA LOCAL INFILE './db/csv/stations.csv'
INTO TABLE stations
CHARSET utf8
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

DELETE FROM rentals;
LOAD DATA LOCAL INFILE './db/csv/rentals.csv'
INTO TABLE rentals
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'

IGNORE 1 LINES
;


DELETE FROM payments;
LOAD DATA LOCAL INFILE './db/csv/payments.csv'
INTO TABLE payments
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'

IGNORE 1 LINES
;
