name: Run API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci
        working-directory: ./vteam-backend

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./vteam-backend